server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ART3RY-G1N/online-learning-platform-configs.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          search-paths: '{application}'
          default-label: main
          skip-ssl-validation: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
